# .cmake-format.yaml
# Configuration for cmake-format, a utility to format CMake scripts.

line_width: 120
tab_size: 4
use_tabchars: False
dangle_parens: True
dangle_align: prefix
line_ending: windows
autosort: True
command_case: lower
separate_ctrl_name_with_space: false
separate_fn_name_with_space: false
