
CC=g++
CFLAGS=-g -Wall -Wextra -Wpedantic
OPTFLAG=-O2
CXXSTD=-std=c++11

factory:factory.cpp
	$(CC) $(CFLAGS) $(OPTFLAG) $(CXXSTD) -c factory.cpp -o factory.exe

singleton:singleton.cpp
	$(CC) $(CFLAGS) $(OPTFLAG) $(CXXSTD) -c singleton.cpp -o singleton.exe
