# Topic: Mini project - 2
# Number guessing game
# Ask user to guess a number and provide instruction leading to the correct answer
# Author: Xuhua Huang
#
# Last updated: June 10, 2021
# Created on: June 10, 2021

import random


def main():
    # greet user
    print("Welcome to random number guessing game")
    # ask for upper bound
    top_of_range = input("Please type a number: ")
    if top_of_range.isdigit():
        top_of_range = int(top_of_range)
        if top_of_range <= 0:
            print("Please enter a number greater than 0 next time")
            quit()
    else:
        print("Error! Expecting a number!")
        quit()

    guesses = 0
    random_number = random.randint(0, top_of_range)  # [0, top_of_range]
    # print(f"Random number generated: {random_number}.")  # for testing purpose only
    # enter the guessing loop
    while True:
        user_guess = input("Please enter you guess: ")
        # determine the input type
        if user_guess.isdigit():
            guesses += 1  # increment
            user_guess = int(user_guess)
            # compare user_guess to the random number generated by the program
            if user_guess < random_number:
                print("Enter a number that is greater than your current guess")
            elif user_guess > random_number:
                print("Enter a number that is smaller than your current guess")
            else:
                print(f"Correct! The correct answer is {random_number}.")
                break
        else:  # input was not a number
            print("Please enter a number: ")
            continue

    print(f"Your total guesses is {guesses}.")


if __name__ == '__main__':
    main()
