
CC=g++
CFLAGS=-g -Wall
OPTFLAG=-O2

ikm:IKMTestQuestion.cpp
	$(CC) $(CFLAGS) $(OPTFLAG) -c IKMTestQuestion.cpp -o ikm.exe

matrox:MatroxTestQuestion.cpp
	$(CC) $(CFLAGS) $(OPTFLAG) -c MatroxTestQuestion.cpp -o matrox.exe

rossvideo:RossVideoTestQuestion.cpp
	$(CC) $(CFLAGS) $(OPTFLAG) -c RossVideoTestQuestion.cpp  -o rossvideo.exe

clean:
	rm -f *.exe *.o
