name: codecov
on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main
      - develop

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  codecov:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
